name: "Step 1: Analyze Project Data"

on:
  workflow_dispatch:
    inputs:
      source_project:
        description: 'Source project code'
        required: true
        default: 'INTEGRATIO'
      target_project:
        description: 'Target project code'
        required: true
        default: 'INTEGRATIO'
      after_date:
        description: 'Date to filter runs after (ISO format)'
        required: true
        default: '2025-08-18T00:00:00Z'

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build analyzer
      run: go build -o analyze-project ./cmd/analyze-project
      
    - name: Run project analysis
      env:
        QASE_SOURCE_API_TOKEN: ${{ secrets.QASE_SOURCE_API_TOKEN }}
        QASE_TARGET_API_TOKEN: ${{ secrets.QASE_TARGET_API_TOKEN }}
        QASE_SOURCE_PROJECT: ${{ inputs.source_project }}
        QASE_TARGET_PROJECT: ${{ inputs.target_project }}
        QASE_AFTER_DATE: ${{ inputs.after_date }}
      run: |
        echo "=== Project Analysis ==="
        ./analyze-project
        
    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: project-analysis
        path: analysis-results.json
        retention-days: 30
