name: "Step 2: Fetch Test Runs"

on:
  workflow_dispatch:
    inputs:
      source_project:
        description: 'Source project code'
        required: true
        default: 'INTEGRATIO'
      after_date:
        description: 'Date to filter runs after (ISO format)'
        required: true
        default: '2025-08-18T00:00:00Z'

jobs:
  fetch-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build run fetcher
      run: go build -o fetch-runs ./cmd/fetch-runs
      
    - name: Fetch test runs
      env:
        QASE_SOURCE_API_TOKEN: ${{ secrets.QASE_SOURCE_API_TOKEN }}
        QASE_SOURCE_PROJECT: ${{ inputs.source_project }}
        QASE_AFTER_DATE: ${{ inputs.after_date }}
      run: |
        echo "=== Fetching Test Runs ==="
        ./fetch-runs
        
    - name: Upload runs data
      uses: actions/upload-artifact@v4
      with:
        name: test-runs
        path: runs-data.json
        retention-days: 30
