name: "Step 4: Migrate Data"

on:
  workflow_dispatch:
    inputs:
      source_project:
        description: 'Source project code'
        required: true
        default: 'INTEGRATIO'
      target_project:
        description: 'Target project code'
        required: true
        default: 'INTEGRATIO'
      match_mode:
        description: 'Case matching mode'
        required: true
        default: 'custom_field'
        type: choice
        options:
        - custom_field
        - csv
      cf_id:
        description: 'Custom field ID (for custom_field mode)'
        required: false
        default: '2'
      dry_run:
        description: 'Dry run mode'
        required: true
        default: true
        type: boolean

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Download previous artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-runs
        path: ./data/
        
    - name: Download results data
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./data/
        
    - name: Build migrator
      run: go build -o migrate-data ./cmd/migrate-data
      
    - name: Run migration
      env:
        QASE_SOURCE_API_TOKEN: ${{ secrets.QASE_SOURCE_API_TOKEN }}
        QASE_TARGET_API_TOKEN: ${{ secrets.QASE_TARGET_API_TOKEN }}
        QASE_SOURCE_PROJECT: ${{ inputs.source_project }}
        QASE_TARGET_PROJECT: ${{ inputs.target_project }}
        QASE_MATCH_MODE: ${{ inputs.match_mode }}
        QASE_CF_ID: ${{ inputs.cf_id }}
        QASE_DRY_RUN: ${{ inputs.dry_run }}
      run: |
        echo "=== Migrating Data ==="
        ./migrate-data
        
    - name: Upload migration results
      uses: actions/upload-artifact@v4
      with:
        name: migration-results
        path: migration-results.json
        retention-days: 30
