name: Cross-Workspace Test Run Migration

on:
  workflow_dispatch:
    inputs:
      after_date:
        description: 'Only migrate runs created after this date (RFC3339 format)'
        required: false
        default: '2025-08-18T00:00:00Z'
        type: string
      match_mode:
        description: 'Mapping mode'
        required: false
        default: 'custom_field'
        type: choice
        options:
          - custom_field
          - csv
      cf_id:
        description: 'Custom field ID (required for custom_field mode)'
        required: false
        default: '1'
        type: string
      dry_run:
        description: 'Dry run mode'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Run migration
      env:
        QASE_SOURCE_API_TOKEN: ${{ secrets.QASE_TOKEN_WS_A }}
        QASE_TARGET_API_TOKEN: ${{ secrets.QASE_TOKEN_WS_B }}
        QASE_SOURCE_PROJECT: ${{ vars.QASE_SOURCE_PROJECT }}
        QASE_TARGET_PROJECT: ${{ vars.QASE_TARGET_PROJECT }}
        QASE_AFTER_DATE: ${{ inputs.after_date }}
        QASE_MATCH_MODE: ${{ inputs.match_mode }}
        QASE_CF_ID: ${{ inputs.cf_id }}
        QASE_DRY_RUN: ${{ inputs.dry_run }}
      run: |
        go run .
        
    - name: Upload mapping artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: case-mapping
        path: case_map.out.csv
        retention-days: 30
        if-no-files-found: ignore
